---
name: Lint
"on":
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts ./init_db'

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.3.0

      - name: Run Yamllint
        run: |
          pip install yamllint
          yamllint .

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npx eslint ./src
